name: PluginGradle
version: 0.1
main: org.example.App
api-version: "1.21.11"
commands:
  menu:
    description: "use this to open a sample menu"
    usage: "/menu"
  rainbow:
    description: "displays a rainbow greeting"
    usage: "/rainbow"
  togglesync:
    description: "toggles whether the player syncs"
    usage: "/togglesync <player> <state>"
  tpoverworld:
    description: "teleports user to the same coordinates in the overworld"
    usage: "/tpoverworld"
  tpmirror:
    description: "teleports user to the same coordinates in the mirror world"
    usage: "/tpmirror"
  startlevel:
    description: "gets two players started on some chud level"
    usage: "/startlevel <level> <player1> <player2>"
