/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
    id("com.gradleup.shadow") version "9.0.0-beta12"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
      name = "papermc"
      url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        name= "tcoded-releases"
        url = uri("https://repo.tcoded.com/releases")
    }

    maven {
        name = "PlugManX"
        url = uri("https://raw.githubusercontent.com/Test-Account666/PlugManX/repository")
    }

}

dependencies {
    paperweight.paperDevBundle("1.21.11-R0.1-SNAPSHOT")
    implementation("com.rylinaux:plugman-bukkit:3.0.2")
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<Copy>("copyJar") {
    from(tasks.named("jar"))
    into("./run/plugins")
}

tasks.register<Exec>("reload") {
    workingDir("./run")
    commandLine("mcrcon", "-H", "localhost", "-p", "mypassword", "plugman reload all")
    dependsOn("copyJar")
}

tasks.register<Exec>("restart") {
    workingDir("./run")
    commandLine("mcrcon", "-H", "localhost", "-p", "mypassword", "restart")
    dependsOn("copyJar")
}

tasks.register<Exec>("shutdown") {
    workingDir("./run")
    commandLine("mcrcon", "-H", "localhost", "-p", "mypassword", "stop")
}

tasks.register<Exec>("launch") {
    workingDir("./run")
    commandLine("java",
        "-jar",
        "paper.jar",
        "--nogui",)
    dependsOn("copyJar")
    dependsOn("shutdown")
}

tasks.named("build") {
    finalizedBy("restart")
}

tasks.assemble {
    paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION
}
